parameters:
#    game_utilisateur.example.class: Game\UtilisateurBundle\Example

services:
#    game_utilisateur.example:
#        class: %game_utilisateur.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
